# Generated by Django 2.2.4 on 2020-02-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20200221_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='points',
        ),
        migrations.AddField(
            model_name='point',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='points.Category'),
        ),
    ]
