# Generated by Django 2.2.4 on 2020-02-26 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0004_bookmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookmarks',
            new_name='bookmark',
        ),
    ]
